// Copyright (c) 2024 guanguans<ityaozm@gmail.com>
// For the full copyright and license information, please view
// the LICENSE file that was distributed with this source code.
// https://github.com/guanguans/gh-actions-watcher

// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package enum

import (
	"fmt"
	"strings"
)

const (
	// RunConclusionActionRequired is a RunConclusion of type action_required.
	RunConclusionActionRequired RunConclusion = "action_required"
	// RunConclusionCancelled is a RunConclusion of type cancelled.
	RunConclusionCancelled RunConclusion = "cancelled"
	// RunConclusionFailure is a RunConclusion of type failure.
	RunConclusionFailure RunConclusion = "failure"
	// RunConclusionNeutral is a RunConclusion of type neutral.
	RunConclusionNeutral RunConclusion = "neutral"
	// RunConclusionSuccess is a RunConclusion of type success.
	RunConclusionSuccess RunConclusion = "success"
	// RunConclusionSkipped is a RunConclusion of type skipped.
	RunConclusionSkipped RunConclusion = "skipped"
	// RunConclusionStale is a RunConclusion of type stale.
	RunConclusionStale RunConclusion = "stale"
	// RunConclusionTimedOut is a RunConclusion of type timed_out.
	RunConclusionTimedOut RunConclusion = "timed_out"
)

var ErrInvalidRunConclusion = fmt.Errorf("not a valid RunConclusion, try [%s]", strings.Join(_RunConclusionNames, ", "))

var _RunConclusionNames = []string{
	string(RunConclusionActionRequired),
	string(RunConclusionCancelled),
	string(RunConclusionFailure),
	string(RunConclusionNeutral),
	string(RunConclusionSuccess),
	string(RunConclusionSkipped),
	string(RunConclusionStale),
	string(RunConclusionTimedOut),
}

// RunConclusionNames returns a list of possible string values of RunConclusion.
func RunConclusionNames() []string {
	tmp := make([]string, len(_RunConclusionNames))
	copy(tmp, _RunConclusionNames)
	return tmp
}

// RunConclusionValues returns a list of the values for RunConclusion
func RunConclusionValues() []RunConclusion {
	return []RunConclusion{
		RunConclusionActionRequired,
		RunConclusionCancelled,
		RunConclusionFailure,
		RunConclusionNeutral,
		RunConclusionSuccess,
		RunConclusionSkipped,
		RunConclusionStale,
		RunConclusionTimedOut,
	}
}

// String implements the Stringer interface.
func (x RunConclusion) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RunConclusion) IsValid() bool {
	_, err := ParseRunConclusion(string(x))
	return err == nil
}

var _RunConclusionValue = map[string]RunConclusion{
	"action_required": RunConclusionActionRequired,
	"cancelled":       RunConclusionCancelled,
	"failure":         RunConclusionFailure,
	"neutral":         RunConclusionNeutral,
	"success":         RunConclusionSuccess,
	"skipped":         RunConclusionSkipped,
	"stale":           RunConclusionStale,
	"timed_out":       RunConclusionTimedOut,
}

// ParseRunConclusion attempts to convert a string to a RunConclusion.
func ParseRunConclusion(name string) (RunConclusion, error) {
	if x, ok := _RunConclusionValue[name]; ok {
		return x, nil
	}
	return RunConclusion(""), fmt.Errorf("%s is %w", name, ErrInvalidRunConclusion)
}

// MarshalText implements the text marshaller method.
func (x RunConclusion) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *RunConclusion) UnmarshalText(text []byte) error {
	tmp, err := ParseRunConclusion(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Set implements the Golang flag.Value interface func.
func (x *RunConclusion) Set(val string) error {
	v, err := ParseRunConclusion(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *RunConclusion) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *RunConclusion) Type() string {
	return "RunConclusion"
}
